name: Test Compile

on:
  push:

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: 'arduino:avr:uno'
          sketch-paths: |
            - src/PlantIncubator
          libraries: '- source-path: ./src/Libraries/'