name: Test Compile

on:
  push:

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: 'arduino:avr:uno'
          sketch-paths: |
            - src/PlantIncubator
          libraries: |
            - name: A4988MotorController
              source-path: src/Libraries/A4988MotorController
            - name: EndstopController
              source-path: src/Libraries/EndstopController
            - name: LightController
              source-path: src/Libraries/LightController